name: PHP Composer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Report PHP version
        # run: php -v
      # - name: Run a one-line script
        # run: echo Hello, world!
      # - name: Run a other script
        # run: echo Hello, Mr.Hoan!
      
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        # env:
          # TEST_NAME: HoanChuong
        with:
          # bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          memory_limit: 256M
          # args: --coverage-text

