name: PHP Composer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Report PHP version
        run: php -v
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a other script
        run: echo Hello, Mr.Hoan!

